const head = document.getElementById("head");
const land = document.getElementById("land");
const skils = document.getElementById("skils");
const skil_1 = document.getElementById("skil-1");
const skil_2 = document.getElementById("skil-2");
const skil_3 = document.getElementById("skil-3");
const skil_4 = document.getElementById("skil-4");
const serv = document.getElementById("serv");
const work = document.getElementById("work");
const foot = document.getElementById("footer");
const btn = document.getElementById("btn");
const btn_2 = document.getElementById("btn2");
const i = document.getElementById("i");
const i2 = document.getElementById("i2");
const pp = document.getElementById("pp");
const hh = document.getElementById("hh");
const ul = document.getElementById("ul");
const card_1 = document.getElementById("card-1");
const card_2 = document.getElementById("card-2");
const card_3 = document.getElementById("card-3");
const crt_1 = document.getElementById("crt1");
const crt_2 = document.getElementById("crt2");
const crt_3 = document.getElementById("crt3");
const portf = document.getElementById("port");

btn.onclick = function light() {
     head.style.backgroundColor = "rgb(240, 240, 240)"
     document.body.style.backgroundColor = "#fafafa"
     i.style.color = "#eee"
     i2.style.color = "#eee"
     skils.style.backgroundColor = "#ba8118"
     skil_1.style.backgroundColor = "#eee"
     skil_2.style.backgroundColor = "#eee"
     skil_3.style.backgroundColor = "#eee"
     skil_4.style.backgroundColor = "#eee"
     skil_1.style.color = "#ba8118"
     skil_1.style.border = "none"
     skil_2.style.color = "#ba8118"
     skil_2.style.border = "none"
     skil_3.style.color = "#ba8118"
     skil_3.style.border = "none"
     skil_4.style.color = "#ba8118"
     skil_4.style.border = "none"
     work.style.backgroundColor = "#fafafa"
     card_1.style.backgroundColor = "#eee"
     card_2.style.backgroundColor = "#eee"
     card_3.style.backgroundColor = "#eee"
     crt_1.style.backgroundColor = "#eee"
     crt_2.style.backgroundColor = "#eee"
     crt_3.style.backgroundColor = "#eee"
     foot.style.backgroundColor = "rgb(240, 240, 240)"
     ul.style.backgroundColor = "#eee"
     ul.style.borderBottomColor = "none"
     hh.style.color = "rgb(240, 240, 240)"
     pp.style.color = "rgb(240, 240, 240)"
     head.style.backgroundColor = "rgb(240, 240, 240)"
     footer.style.backgroundColor = "rgb(240, 240, 240)"
     document.body.style.backgroundColor = "#fafafa"
}
btn_2.onclick = function dark() {
     head.style.backgroundColor = "#1c1c1c"
     document.body.style.backgroundColor = "#1f1f1f"
     i.style.color = "#1c1c1c"
     i2.style.color = "#1c1c1c"
     skils.style.backgroundColor = "#ba8118"
     skil_1.style.backgroundColor = "#1f1f1f"
     skil_2.style.backgroundColor = "#1f1f1f"
     skil_3.style.backgroundColor = "#1f1f1f"
     skil_4.style.backgroundColor = "#1f1f1f"
     skil_1.style.color = "#ba8118"
     skil_2.style.color = "#ba8118"
     skil_3.style.color = "#ba8118"
     skil_4.style.color = "#ba8118"
     work.style.backgroundColor = "#1f1f1f"
     card_1.style.backgroundColor = "#1c1c1c"
     card_2.style.backgroundColor = "#1c1c1c"
     card_3.style.backgroundColor = "#1c1c1c"
     crt_1.style.backgroundColor = "#1c1c1c"
     crt_2.style.backgroundColor = "#1c1c1c"
     crt_3.style.backgroundColor = "#1c1c1c"
     foot.style.backgroundColor = "#1c1c1c"
     ul.style.backgroundColor = "#242424"
     hh.style.color = "#1c1c1c"
     pp.style.color = "#1c1c1c"
     // head.style.backgroundColor = "rgb(240, 240, 240)"
     footer.style.backgroundColor = "#1c1c1c"
     // document.body.style.backgroundColor = "#fafafa"
}